name: release
# Trigger Method.
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    # Write permissions must be set because a release needs to be created.
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Back up the repository
        uses: actions/checkout@v4

      - name: Install the stable version of Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up the Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up the Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install the prerequisites
        run: bun install

      - name: Read release notes
        id: read-notes
        run: |
          $DATE = Get-Date -Format "MM月dd日yyyy年"

          $NOTES = Get-Content .github/workflows/markdown/release.md -Raw
          $NOTES = $NOTES -replace '__DATE__', $DATE
          
          $NOTES = $NOTES -replace '%', '%25'
          
          echo "notes=$NOTES" >> $env:GITHUB_OUTPUT

        # Use Tauri operations.
      - name: Build the application
        id: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Private Key.
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY}}
          # Private Key Password.
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: release-v__VERSION__
          releaseName: "Version v__VERSION__"
          releaseBody: ${{ steps.read-notes.outputs.notes }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
